# Generated by Django 5.0.2 on 2024-03-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_productaccess_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_start',
            field=models.DateField(),
        ),
    ]
